// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BoxMsg.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "BoxMsg.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
// @@protoc_insertion_point(includes)

namespace com {
namespace road {
namespace yishi {
namespace proto {
namespace box {

void protobuf_ShutdownFile_BoxMsg_2eproto() {
  delete BoxMsg::default_instance_;
  delete BoxStarMsg::default_instance_;
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
void protobuf_AddDesc_BoxMsg_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#else
void protobuf_AddDesc_BoxMsg_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#endif
  BoxMsg::default_instance_ = new BoxMsg();
  BoxStarMsg::default_instance_ = new BoxStarMsg();
  BoxMsg::default_instance_->InitAsDefaultInstance();
  BoxStarMsg::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_BoxMsg_2eproto);
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_BoxMsg_2eproto_once_);
void protobuf_AddDesc_BoxMsg_2eproto() {
  ::google::protobuf::::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_BoxMsg_2eproto_once_,
                 &protobuf_AddDesc_BoxMsg_2eproto_impl);
}
#else
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_BoxMsg_2eproto {
  StaticDescriptorInitializer_BoxMsg_2eproto() {
    protobuf_AddDesc_BoxMsg_2eproto();
  }
} static_descriptor_initializer_BoxMsg_2eproto_;
#endif

// ===================================================================

#ifndef _MSC_VER
const int BoxMsg::kTimeFieldNumber;
const int BoxMsg::kGradeFieldNumber;
const int BoxMsg::kOperateFieldNumber;
const int BoxMsg::kTimerunFieldNumber;
#endif  // !_MSC_VER

BoxMsg::BoxMsg()
  : ::google::protobuf::MessageLite() {
  SharedCtor();
}

void BoxMsg::InitAsDefaultInstance() {
}

BoxMsg::BoxMsg(const BoxMsg& from)
  : ::google::protobuf::MessageLite() {
  SharedCtor();
  MergeFrom(from);
}

void BoxMsg::SharedCtor() {
  _cached_size_ = 0;
  time_ = 0;
  grade_ = 0;
  operate_ = false;
  timerun_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

BoxMsg::~BoxMsg() {
  SharedDtor();
}

void BoxMsg::SharedDtor() {
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
  }
}

void BoxMsg::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const BoxMsg& BoxMsg::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_BoxMsg_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_BoxMsg_2eproto();
#endif
  return *default_instance_;
}

BoxMsg* BoxMsg::default_instance_ = NULL;

BoxMsg* BoxMsg::New() const {
  return new BoxMsg;
}

void BoxMsg::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    time_ = 0;
    grade_ = 0;
    operate_ = false;
    timerun_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

bool BoxMsg::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 time = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &time_)));
          set_has_time();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_grade;
        break;
      }

      // optional int32 grade = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_grade:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &grade_)));
          set_has_grade();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_operate;
        break;
      }

      // optional bool operate = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_operate:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &operate_)));
          set_has_operate();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(32)) goto parse_timerun;
        break;
      }

      // optional int32 timerun = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_timerun:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &timerun_)));
          set_has_timerun();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void BoxMsg::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional int32 time = 1;
  if (has_time()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->time(), output);
  }

  // optional int32 grade = 2;
  if (has_grade()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->grade(), output);
  }

  // optional bool operate = 3;
  if (has_operate()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(3, this->operate(), output);
  }

  // optional int32 timerun = 4;
  if (has_timerun()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->timerun(), output);
  }

}

int BoxMsg::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional int32 time = 1;
    if (has_time()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->time());
    }

    // optional int32 grade = 2;
    if (has_grade()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->grade());
    }

    // optional bool operate = 3;
    if (has_operate()) {
      total_size += 1 + 1;
    }

    // optional int32 timerun = 4;
    if (has_timerun()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->timerun());
    }

  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void BoxMsg::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const BoxMsg*>(&from));
}

void BoxMsg::MergeFrom(const BoxMsg& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_time()) {
      set_time(from.time());
    }
    if (from.has_grade()) {
      set_grade(from.grade());
    }
    if (from.has_operate()) {
      set_operate(from.operate());
    }
    if (from.has_timerun()) {
      set_timerun(from.timerun());
    }
  }
}

void BoxMsg::CopyFrom(const BoxMsg& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BoxMsg::IsInitialized() const {

  return true;
}

void BoxMsg::Swap(BoxMsg* other) {
  if (other != this) {
    std::swap(time_, other->time_);
    std::swap(grade_, other->grade_);
    std::swap(operate_, other->operate_);
    std::swap(timerun_, other->timerun_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::std::string BoxMsg::GetTypeName() const {
  return "com.road.yishi.proto.box.BoxMsg";
}


// ===================================================================

#ifndef _MSC_VER
const int BoxStarMsg::kTimerunFieldNumber;
#endif  // !_MSC_VER

BoxStarMsg::BoxStarMsg()
  : ::google::protobuf::MessageLite() {
  SharedCtor();
}

void BoxStarMsg::InitAsDefaultInstance() {
}

BoxStarMsg::BoxStarMsg(const BoxStarMsg& from)
  : ::google::protobuf::MessageLite() {
  SharedCtor();
  MergeFrom(from);
}

void BoxStarMsg::SharedCtor() {
  _cached_size_ = 0;
  timerun_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

BoxStarMsg::~BoxStarMsg() {
  SharedDtor();
}

void BoxStarMsg::SharedDtor() {
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
  }
}

void BoxStarMsg::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const BoxStarMsg& BoxStarMsg::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_BoxMsg_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_BoxMsg_2eproto();
#endif
  return *default_instance_;
}

BoxStarMsg* BoxStarMsg::default_instance_ = NULL;

BoxStarMsg* BoxStarMsg::New() const {
  return new BoxStarMsg;
}

void BoxStarMsg::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    timerun_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

bool BoxStarMsg::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 timerun = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &timerun_)));
          set_has_timerun();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void BoxStarMsg::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional int32 timerun = 1;
  if (has_timerun()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->timerun(), output);
  }

}

int BoxStarMsg::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional int32 timerun = 1;
    if (has_timerun()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->timerun());
    }

  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void BoxStarMsg::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const BoxStarMsg*>(&from));
}

void BoxStarMsg::MergeFrom(const BoxStarMsg& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_timerun()) {
      set_timerun(from.timerun());
    }
  }
}

void BoxStarMsg::CopyFrom(const BoxStarMsg& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BoxStarMsg::IsInitialized() const {

  return true;
}

void BoxStarMsg::Swap(BoxStarMsg* other) {
  if (other != this) {
    std::swap(timerun_, other->timerun_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::std::string BoxStarMsg::GetTypeName() const {
  return "com.road.yishi.proto.box.BoxStarMsg";
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace box
}  // namespace proto
}  // namespace yishi
}  // namespace road
}  // namespace com

// @@protoc_insertion_point(global_scope)
