// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AppellExchange.proto

#ifndef PROTOBUF_AppellExchange_2eproto__INCLUDED
#define PROTOBUF_AppellExchange_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
// @@protoc_insertion_point(includes)

namespace com {
namespace road {
namespace yishi {
namespace proto {
namespace player {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_AppellExchange_2eproto();
void protobuf_AssignDesc_AppellExchange_2eproto();
void protobuf_ShutdownFile_AppellExchange_2eproto();

class AppellExchangeMsg;

// ===================================================================

class AppellExchangeMsg : public ::google::protobuf::MessageLite {
 public:
  AppellExchangeMsg();
  virtual ~AppellExchangeMsg();

  AppellExchangeMsg(const AppellExchangeMsg& from);

  inline AppellExchangeMsg& operator=(const AppellExchangeMsg& from) {
    CopyFrom(from);
    return *this;
  }

  static const AppellExchangeMsg& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const AppellExchangeMsg* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(AppellExchangeMsg* other);

  // implements Message ----------------------------------------------

  AppellExchangeMsg* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const AppellExchangeMsg& from);
  void MergeFrom(const AppellExchangeMsg& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 appellId = 1;
  inline bool has_appellid() const;
  inline void clear_appellid();
  static const int kAppellIdFieldNumber = 1;
  inline ::google::protobuf::int32 appellid() const;
  inline void set_appellid(::google::protobuf::int32 value);

  // optional bool look = 2;
  inline bool has_look() const;
  inline void clear_look();
  static const int kLookFieldNumber = 2;
  inline bool look() const;
  inline void set_look(bool value);

  // @@protoc_insertion_point(class_scope:com.road.yishi.proto.player.AppellExchangeMsg)
 private:
  inline void set_has_appellid();
  inline void clear_has_appellid();
  inline void set_has_look();
  inline void clear_has_look();

  ::google::protobuf::int32 appellid_;
  bool look_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_AppellExchange_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_AppellExchange_2eproto();
  #endif
  friend void protobuf_AssignDesc_AppellExchange_2eproto();
  friend void protobuf_ShutdownFile_AppellExchange_2eproto();

  void InitAsDefaultInstance();
  static AppellExchangeMsg* default_instance_;
};
// ===================================================================


// ===================================================================

// AppellExchangeMsg

// optional int32 appellId = 1;
inline bool AppellExchangeMsg::has_appellid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void AppellExchangeMsg::set_has_appellid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void AppellExchangeMsg::clear_has_appellid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void AppellExchangeMsg::clear_appellid() {
  appellid_ = 0;
  clear_has_appellid();
}
inline ::google::protobuf::int32 AppellExchangeMsg::appellid() const {
  return appellid_;
}
inline void AppellExchangeMsg::set_appellid(::google::protobuf::int32 value) {
  set_has_appellid();
  appellid_ = value;
}

// optional bool look = 2;
inline bool AppellExchangeMsg::has_look() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void AppellExchangeMsg::set_has_look() {
  _has_bits_[0] |= 0x00000002u;
}
inline void AppellExchangeMsg::clear_has_look() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void AppellExchangeMsg::clear_look() {
  look_ = false;
  clear_has_look();
}
inline bool AppellExchangeMsg::look() const {
  return look_;
}
inline void AppellExchangeMsg::set_look(bool value) {
  set_has_look();
  look_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace player
}  // namespace proto
}  // namespace yishi
}  // namespace road
}  // namespace com

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_AppellExchange_2eproto__INCLUDED
