// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChallengeCoolTime.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "ChallengeCoolTime.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
// @@protoc_insertion_point(includes)

namespace com {
namespace road {
namespace yishi {
namespace proto {
namespace player {

void protobuf_ShutdownFile_ChallengeCoolTime_2eproto() {
  delete ChallengeCoolTimeMsg::default_instance_;
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
void protobuf_AddDesc_ChallengeCoolTime_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#else
void protobuf_AddDesc_ChallengeCoolTime_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#endif
  ChallengeCoolTimeMsg::default_instance_ = new ChallengeCoolTimeMsg();
  ChallengeCoolTimeMsg::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_ChallengeCoolTime_2eproto);
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_ChallengeCoolTime_2eproto_once_);
void protobuf_AddDesc_ChallengeCoolTime_2eproto() {
  ::google::protobuf::::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_ChallengeCoolTime_2eproto_once_,
                 &protobuf_AddDesc_ChallengeCoolTime_2eproto_impl);
}
#else
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_ChallengeCoolTime_2eproto {
  StaticDescriptorInitializer_ChallengeCoolTime_2eproto() {
    protobuf_AddDesc_ChallengeCoolTime_2eproto();
  }
} static_descriptor_initializer_ChallengeCoolTime_2eproto_;
#endif

// ===================================================================

#ifndef _MSC_VER
const int ChallengeCoolTimeMsg::kLeftTimeFieldNumber;
const int ChallengeCoolTimeMsg::kChallengeCountFieldNumber;
const int ChallengeCoolTimeMsg::kTotalCountFieldNumber;
const int ChallengeCoolTimeMsg::kTypeFieldNumber;
const int ChallengeCoolTimeMsg::kTotalBuyCountFieldNumber;
#endif  // !_MSC_VER

ChallengeCoolTimeMsg::ChallengeCoolTimeMsg()
  : ::google::protobuf::MessageLite() {
  SharedCtor();
}

void ChallengeCoolTimeMsg::InitAsDefaultInstance() {
}

ChallengeCoolTimeMsg::ChallengeCoolTimeMsg(const ChallengeCoolTimeMsg& from)
  : ::google::protobuf::MessageLite() {
  SharedCtor();
  MergeFrom(from);
}

void ChallengeCoolTimeMsg::SharedCtor() {
  _cached_size_ = 0;
  left_time_ = 0;
  challenge_count_ = 0;
  total_count_ = 0;
  type_ = 0;
  total_buycount_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ChallengeCoolTimeMsg::~ChallengeCoolTimeMsg() {
  SharedDtor();
}

void ChallengeCoolTimeMsg::SharedDtor() {
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
  }
}

void ChallengeCoolTimeMsg::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ChallengeCoolTimeMsg& ChallengeCoolTimeMsg::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_ChallengeCoolTime_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_ChallengeCoolTime_2eproto();
#endif
  return *default_instance_;
}

ChallengeCoolTimeMsg* ChallengeCoolTimeMsg::default_instance_ = NULL;

ChallengeCoolTimeMsg* ChallengeCoolTimeMsg::New() const {
  return new ChallengeCoolTimeMsg;
}

void ChallengeCoolTimeMsg::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    left_time_ = 0;
    challenge_count_ = 0;
    total_count_ = 0;
    type_ = 0;
    total_buycount_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

bool ChallengeCoolTimeMsg::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 left_time = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &left_time_)));
          set_has_left_time();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_challenge_count;
        break;
      }

      // optional int32 challenge_count = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_challenge_count:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &challenge_count_)));
          set_has_challenge_count();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_total_count;
        break;
      }

      // optional int32 total_count = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_total_count:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &total_count_)));
          set_has_total_count();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(32)) goto parse_type;
        break;
      }

      // optional int32 type = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_type:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &type_)));
          set_has_type();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(40)) goto parse_total_buyCount;
        break;
      }

      // optional int32 total_buyCount = 5;
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_total_buyCount:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &total_buycount_)));
          set_has_total_buycount();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void ChallengeCoolTimeMsg::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional int32 left_time = 1;
  if (has_left_time()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->left_time(), output);
  }

  // optional int32 challenge_count = 2;
  if (has_challenge_count()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->challenge_count(), output);
  }

  // optional int32 total_count = 3;
  if (has_total_count()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->total_count(), output);
  }

  // optional int32 type = 4;
  if (has_type()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->type(), output);
  }

  // optional int32 total_buyCount = 5;
  if (has_total_buycount()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->total_buycount(), output);
  }

}

int ChallengeCoolTimeMsg::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional int32 left_time = 1;
    if (has_left_time()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->left_time());
    }

    // optional int32 challenge_count = 2;
    if (has_challenge_count()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->challenge_count());
    }

    // optional int32 total_count = 3;
    if (has_total_count()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->total_count());
    }

    // optional int32 type = 4;
    if (has_type()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->type());
    }

    // optional int32 total_buyCount = 5;
    if (has_total_buycount()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->total_buycount());
    }

  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ChallengeCoolTimeMsg::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const ChallengeCoolTimeMsg*>(&from));
}

void ChallengeCoolTimeMsg::MergeFrom(const ChallengeCoolTimeMsg& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_left_time()) {
      set_left_time(from.left_time());
    }
    if (from.has_challenge_count()) {
      set_challenge_count(from.challenge_count());
    }
    if (from.has_total_count()) {
      set_total_count(from.total_count());
    }
    if (from.has_type()) {
      set_type(from.type());
    }
    if (from.has_total_buycount()) {
      set_total_buycount(from.total_buycount());
    }
  }
}

void ChallengeCoolTimeMsg::CopyFrom(const ChallengeCoolTimeMsg& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ChallengeCoolTimeMsg::IsInitialized() const {

  return true;
}

void ChallengeCoolTimeMsg::Swap(ChallengeCoolTimeMsg* other) {
  if (other != this) {
    std::swap(left_time_, other->left_time_);
    std::swap(challenge_count_, other->challenge_count_);
    std::swap(total_count_, other->total_count_);
    std::swap(type_, other->type_);
    std::swap(total_buycount_, other->total_buycount_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::std::string ChallengeCoolTimeMsg::GetTypeName() const {
  return "com.road.yishi.proto.player.ChallengeCoolTimeMsg";
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace player
}  // namespace proto
}  // namespace yishi
}  // namespace road
}  // namespace com

// @@protoc_insertion_point(global_scope)
