// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EffectRemoveRsp.proto

#ifndef PROTOBUF_EffectRemoveRsp_2eproto__INCLUDED
#define PROTOBUF_EffectRemoveRsp_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
// @@protoc_insertion_point(includes)

namespace com {
namespace road {
namespace yishi {
namespace proto {
namespace player {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_EffectRemoveRsp_2eproto();
void protobuf_AssignDesc_EffectRemoveRsp_2eproto();
void protobuf_ShutdownFile_EffectRemoveRsp_2eproto();

class EffectRemoveRspMsg;

// ===================================================================

class EffectRemoveRspMsg : public ::google::protobuf::MessageLite {
 public:
  EffectRemoveRspMsg();
  virtual ~EffectRemoveRspMsg();

  EffectRemoveRspMsg(const EffectRemoveRspMsg& from);

  inline EffectRemoveRspMsg& operator=(const EffectRemoveRspMsg& from) {
    CopyFrom(from);
    return *this;
  }

  static const EffectRemoveRspMsg& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const EffectRemoveRspMsg* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(EffectRemoveRspMsg* other);

  // implements Message ----------------------------------------------

  EffectRemoveRspMsg* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const EffectRemoveRspMsg& from);
  void MergeFrom(const EffectRemoveRspMsg& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional bool result = 1;
  inline bool has_result() const;
  inline void clear_result();
  static const int kResultFieldNumber = 1;
  inline bool result() const;
  inline void set_result(bool value);

  // optional int32 templateId = 2;
  inline bool has_templateid() const;
  inline void clear_templateid();
  static const int kTemplateIdFieldNumber = 2;
  inline ::google::protobuf::int32 templateid() const;
  inline void set_templateid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:com.road.yishi.proto.player.EffectRemoveRspMsg)
 private:
  inline void set_has_result();
  inline void clear_has_result();
  inline void set_has_templateid();
  inline void clear_has_templateid();

  bool result_;
  ::google::protobuf::int32 templateid_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_EffectRemoveRsp_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_EffectRemoveRsp_2eproto();
  #endif
  friend void protobuf_AssignDesc_EffectRemoveRsp_2eproto();
  friend void protobuf_ShutdownFile_EffectRemoveRsp_2eproto();

  void InitAsDefaultInstance();
  static EffectRemoveRspMsg* default_instance_;
};
// ===================================================================


// ===================================================================

// EffectRemoveRspMsg

// optional bool result = 1;
inline bool EffectRemoveRspMsg::has_result() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void EffectRemoveRspMsg::set_has_result() {
  _has_bits_[0] |= 0x00000001u;
}
inline void EffectRemoveRspMsg::clear_has_result() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void EffectRemoveRspMsg::clear_result() {
  result_ = false;
  clear_has_result();
}
inline bool EffectRemoveRspMsg::result() const {
  return result_;
}
inline void EffectRemoveRspMsg::set_result(bool value) {
  set_has_result();
  result_ = value;
}

// optional int32 templateId = 2;
inline bool EffectRemoveRspMsg::has_templateid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void EffectRemoveRspMsg::set_has_templateid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void EffectRemoveRspMsg::clear_has_templateid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void EffectRemoveRspMsg::clear_templateid() {
  templateid_ = 0;
  clear_has_templateid();
}
inline ::google::protobuf::int32 EffectRemoveRspMsg::templateid() const {
  return templateid_;
}
inline void EffectRemoveRspMsg::set_templateid(::google::protobuf::int32 value) {
  set_has_templateid();
  templateid_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace player
}  // namespace proto
}  // namespace yishi
}  // namespace road
}  // namespace com

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_EffectRemoveRsp_2eproto__INCLUDED
