// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EffectRemoveRsp.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "EffectRemoveRsp.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
// @@protoc_insertion_point(includes)

namespace com {
namespace road {
namespace yishi {
namespace proto {
namespace player {

void protobuf_ShutdownFile_EffectRemoveRsp_2eproto() {
  delete EffectRemoveRspMsg::default_instance_;
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
void protobuf_AddDesc_EffectRemoveRsp_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#else
void protobuf_AddDesc_EffectRemoveRsp_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#endif
  EffectRemoveRspMsg::default_instance_ = new EffectRemoveRspMsg();
  EffectRemoveRspMsg::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_EffectRemoveRsp_2eproto);
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_EffectRemoveRsp_2eproto_once_);
void protobuf_AddDesc_EffectRemoveRsp_2eproto() {
  ::google::protobuf::::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_EffectRemoveRsp_2eproto_once_,
                 &protobuf_AddDesc_EffectRemoveRsp_2eproto_impl);
}
#else
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_EffectRemoveRsp_2eproto {
  StaticDescriptorInitializer_EffectRemoveRsp_2eproto() {
    protobuf_AddDesc_EffectRemoveRsp_2eproto();
  }
} static_descriptor_initializer_EffectRemoveRsp_2eproto_;
#endif

// ===================================================================

#ifndef _MSC_VER
const int EffectRemoveRspMsg::kResultFieldNumber;
const int EffectRemoveRspMsg::kTemplateIdFieldNumber;
#endif  // !_MSC_VER

EffectRemoveRspMsg::EffectRemoveRspMsg()
  : ::google::protobuf::MessageLite() {
  SharedCtor();
}

void EffectRemoveRspMsg::InitAsDefaultInstance() {
}

EffectRemoveRspMsg::EffectRemoveRspMsg(const EffectRemoveRspMsg& from)
  : ::google::protobuf::MessageLite() {
  SharedCtor();
  MergeFrom(from);
}

void EffectRemoveRspMsg::SharedCtor() {
  _cached_size_ = 0;
  result_ = false;
  templateid_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

EffectRemoveRspMsg::~EffectRemoveRspMsg() {
  SharedDtor();
}

void EffectRemoveRspMsg::SharedDtor() {
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
  }
}

void EffectRemoveRspMsg::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const EffectRemoveRspMsg& EffectRemoveRspMsg::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_EffectRemoveRsp_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_EffectRemoveRsp_2eproto();
#endif
  return *default_instance_;
}

EffectRemoveRspMsg* EffectRemoveRspMsg::default_instance_ = NULL;

EffectRemoveRspMsg* EffectRemoveRspMsg::New() const {
  return new EffectRemoveRspMsg;
}

void EffectRemoveRspMsg::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    result_ = false;
    templateid_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

bool EffectRemoveRspMsg::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional bool result = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &result_)));
          set_has_result();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_templateId;
        break;
      }

      // optional int32 templateId = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_templateId:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &templateid_)));
          set_has_templateid();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void EffectRemoveRspMsg::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional bool result = 1;
  if (has_result()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(1, this->result(), output);
  }

  // optional int32 templateId = 2;
  if (has_templateid()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->templateid(), output);
  }

}

int EffectRemoveRspMsg::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional bool result = 1;
    if (has_result()) {
      total_size += 1 + 1;
    }

    // optional int32 templateId = 2;
    if (has_templateid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->templateid());
    }

  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void EffectRemoveRspMsg::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const EffectRemoveRspMsg*>(&from));
}

void EffectRemoveRspMsg::MergeFrom(const EffectRemoveRspMsg& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_result()) {
      set_result(from.result());
    }
    if (from.has_templateid()) {
      set_templateid(from.templateid());
    }
  }
}

void EffectRemoveRspMsg::CopyFrom(const EffectRemoveRspMsg& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool EffectRemoveRspMsg::IsInitialized() const {

  return true;
}

void EffectRemoveRspMsg::Swap(EffectRemoveRspMsg* other) {
  if (other != this) {
    std::swap(result_, other->result_);
    std::swap(templateid_, other->templateid_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::std::string EffectRemoveRspMsg::GetTypeName() const {
  return "com.road.yishi.proto.player.EffectRemoveRspMsg";
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace player
}  // namespace proto
}  // namespace yishi
}  // namespace road
}  // namespace com

// @@protoc_insertion_point(global_scope)
