// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EffectRemoveReq.proto

#ifndef PROTOBUF_EffectRemoveReq_2eproto__INCLUDED
#define PROTOBUF_EffectRemoveReq_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
// @@protoc_insertion_point(includes)

namespace com {
namespace road {
namespace yishi {
namespace proto {
namespace player {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_EffectRemoveReq_2eproto();
void protobuf_AssignDesc_EffectRemoveReq_2eproto();
void protobuf_ShutdownFile_EffectRemoveReq_2eproto();

class EffectRemoveReqMsg;

// ===================================================================

class EffectRemoveReqMsg : public ::google::protobuf::MessageLite {
 public:
  EffectRemoveReqMsg();
  virtual ~EffectRemoveReqMsg();

  EffectRemoveReqMsg(const EffectRemoveReqMsg& from);

  inline EffectRemoveReqMsg& operator=(const EffectRemoveReqMsg& from) {
    CopyFrom(from);
    return *this;
  }

  static const EffectRemoveReqMsg& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const EffectRemoveReqMsg* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(EffectRemoveReqMsg* other);

  // implements Message ----------------------------------------------

  EffectRemoveReqMsg* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const EffectRemoveReqMsg& from);
  void MergeFrom(const EffectRemoveReqMsg& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 templateId = 1;
  inline bool has_templateid() const;
  inline void clear_templateid();
  static const int kTemplateIdFieldNumber = 1;
  inline ::google::protobuf::int32 templateid() const;
  inline void set_templateid(::google::protobuf::int32 value);

  // optional int32 ownType = 2;
  inline bool has_owntype() const;
  inline void clear_owntype();
  static const int kOwnTypeFieldNumber = 2;
  inline ::google::protobuf::int32 owntype() const;
  inline void set_owntype(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:com.road.yishi.proto.player.EffectRemoveReqMsg)
 private:
  inline void set_has_templateid();
  inline void clear_has_templateid();
  inline void set_has_owntype();
  inline void clear_has_owntype();

  ::google::protobuf::int32 templateid_;
  ::google::protobuf::int32 owntype_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_EffectRemoveReq_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_EffectRemoveReq_2eproto();
  #endif
  friend void protobuf_AssignDesc_EffectRemoveReq_2eproto();
  friend void protobuf_ShutdownFile_EffectRemoveReq_2eproto();

  void InitAsDefaultInstance();
  static EffectRemoveReqMsg* default_instance_;
};
// ===================================================================


// ===================================================================

// EffectRemoveReqMsg

// optional int32 templateId = 1;
inline bool EffectRemoveReqMsg::has_templateid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void EffectRemoveReqMsg::set_has_templateid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void EffectRemoveReqMsg::clear_has_templateid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void EffectRemoveReqMsg::clear_templateid() {
  templateid_ = 0;
  clear_has_templateid();
}
inline ::google::protobuf::int32 EffectRemoveReqMsg::templateid() const {
  return templateid_;
}
inline void EffectRemoveReqMsg::set_templateid(::google::protobuf::int32 value) {
  set_has_templateid();
  templateid_ = value;
}

// optional int32 ownType = 2;
inline bool EffectRemoveReqMsg::has_owntype() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void EffectRemoveReqMsg::set_has_owntype() {
  _has_bits_[0] |= 0x00000002u;
}
inline void EffectRemoveReqMsg::clear_has_owntype() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void EffectRemoveReqMsg::clear_owntype() {
  owntype_ = 0;
  clear_has_owntype();
}
inline ::google::protobuf::int32 EffectRemoveReqMsg::owntype() const {
  return owntype_;
}
inline void EffectRemoveReqMsg::set_owntype(::google::protobuf::int32 value) {
  set_has_owntype();
  owntype_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace player
}  // namespace proto
}  // namespace yishi
}  // namespace road
}  // namespace com

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_EffectRemoveReq_2eproto__INCLUDED
