// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LoginState.proto

#ifndef PROTOBUF_LoginState_2eproto__INCLUDED
#define PROTOBUF_LoginState_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
// @@protoc_insertion_point(includes)

namespace com {
namespace road {
namespace yishi {
namespace proto {
namespace player {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_LoginState_2eproto();
void protobuf_AssignDesc_LoginState_2eproto();
void protobuf_ShutdownFile_LoginState_2eproto();

class LoginStateMsg;

// ===================================================================

class LoginStateMsg : public ::google::protobuf::MessageLite {
 public:
  LoginStateMsg();
  virtual ~LoginStateMsg();

  LoginStateMsg(const LoginStateMsg& from);

  inline LoginStateMsg& operator=(const LoginStateMsg& from) {
    CopyFrom(from);
    return *this;
  }

  static const LoginStateMsg& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const LoginStateMsg* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(LoginStateMsg* other);

  // implements Message ----------------------------------------------

  LoginStateMsg* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const LoginStateMsg& from);
  void MergeFrom(const LoginStateMsg& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 player_id = 1;
  inline bool has_player_id() const;
  inline void clear_player_id();
  static const int kPlayerIdFieldNumber = 1;
  inline ::google::protobuf::int32 player_id() const;
  inline void set_player_id(::google::protobuf::int32 value);

  // optional int32 state = 2;
  inline bool has_state() const;
  inline void clear_state();
  static const int kStateFieldNumber = 2;
  inline ::google::protobuf::int32 state() const;
  inline void set_state(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:com.road.yishi.proto.player.LoginStateMsg)
 private:
  inline void set_has_player_id();
  inline void clear_has_player_id();
  inline void set_has_state();
  inline void clear_has_state();

  ::google::protobuf::int32 player_id_;
  ::google::protobuf::int32 state_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_LoginState_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_LoginState_2eproto();
  #endif
  friend void protobuf_AssignDesc_LoginState_2eproto();
  friend void protobuf_ShutdownFile_LoginState_2eproto();

  void InitAsDefaultInstance();
  static LoginStateMsg* default_instance_;
};
// ===================================================================


// ===================================================================

// LoginStateMsg

// optional int32 player_id = 1;
inline bool LoginStateMsg::has_player_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void LoginStateMsg::set_has_player_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void LoginStateMsg::clear_has_player_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void LoginStateMsg::clear_player_id() {
  player_id_ = 0;
  clear_has_player_id();
}
inline ::google::protobuf::int32 LoginStateMsg::player_id() const {
  return player_id_;
}
inline void LoginStateMsg::set_player_id(::google::protobuf::int32 value) {
  set_has_player_id();
  player_id_ = value;
}

// optional int32 state = 2;
inline bool LoginStateMsg::has_state() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void LoginStateMsg::set_has_state() {
  _has_bits_[0] |= 0x00000002u;
}
inline void LoginStateMsg::clear_has_state() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void LoginStateMsg::clear_state() {
  state_ = 0;
  clear_has_state();
}
inline ::google::protobuf::int32 LoginStateMsg::state() const {
  return state_;
}
inline void LoginStateMsg::set_state(::google::protobuf::int32 value) {
  set_has_state();
  state_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace player
}  // namespace proto
}  // namespace yishi
}  // namespace road
}  // namespace com

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_LoginState_2eproto__INCLUDED
