// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MultiCampaignEnterCount.proto

#ifndef PROTOBUF_MultiCampaignEnterCount_2eproto__INCLUDED
#define PROTOBUF_MultiCampaignEnterCount_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
// @@protoc_insertion_point(includes)

namespace com {
namespace road {
namespace yishi {
namespace proto {
namespace player {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_MultiCampaignEnterCount_2eproto();
void protobuf_AssignDesc_MultiCampaignEnterCount_2eproto();
void protobuf_ShutdownFile_MultiCampaignEnterCount_2eproto();

class MultiCampaignEnterCountMsg;

// ===================================================================

class MultiCampaignEnterCountMsg : public ::google::protobuf::MessageLite {
 public:
  MultiCampaignEnterCountMsg();
  virtual ~MultiCampaignEnterCountMsg();

  MultiCampaignEnterCountMsg(const MultiCampaignEnterCountMsg& from);

  inline MultiCampaignEnterCountMsg& operator=(const MultiCampaignEnterCountMsg& from) {
    CopyFrom(from);
    return *this;
  }

  static const MultiCampaignEnterCountMsg& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const MultiCampaignEnterCountMsg* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(MultiCampaignEnterCountMsg* other);

  // implements Message ----------------------------------------------

  MultiCampaignEnterCountMsg* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const MultiCampaignEnterCountMsg& from);
  void MergeFrom(const MultiCampaignEnterCountMsg& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 campaign_count = 1;
  inline bool has_campaign_count() const;
  inline void clear_campaign_count();
  static const int kCampaignCountFieldNumber = 1;
  inline ::google::protobuf::int32 campaign_count() const;
  inline void set_campaign_count(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:com.road.yishi.proto.player.MultiCampaignEnterCountMsg)
 private:
  inline void set_has_campaign_count();
  inline void clear_has_campaign_count();

  ::google::protobuf::int32 campaign_count_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_MultiCampaignEnterCount_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_MultiCampaignEnterCount_2eproto();
  #endif
  friend void protobuf_AssignDesc_MultiCampaignEnterCount_2eproto();
  friend void protobuf_ShutdownFile_MultiCampaignEnterCount_2eproto();

  void InitAsDefaultInstance();
  static MultiCampaignEnterCountMsg* default_instance_;
};
// ===================================================================


// ===================================================================

// MultiCampaignEnterCountMsg

// optional int32 campaign_count = 1;
inline bool MultiCampaignEnterCountMsg::has_campaign_count() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MultiCampaignEnterCountMsg::set_has_campaign_count() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MultiCampaignEnterCountMsg::clear_has_campaign_count() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MultiCampaignEnterCountMsg::clear_campaign_count() {
  campaign_count_ = 0;
  clear_has_campaign_count();
}
inline ::google::protobuf::int32 MultiCampaignEnterCountMsg::campaign_count() const {
  return campaign_count_;
}
inline void MultiCampaignEnterCountMsg::set_campaign_count(::google::protobuf::int32 value) {
  set_has_campaign_count();
  campaign_count_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace player
}  // namespace proto
}  // namespace yishi
}  // namespace road
}  // namespace com

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_MultiCampaignEnterCount_2eproto__INCLUDED
