// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OfflineReward.proto

#ifndef PROTOBUF_OfflineReward_2eproto__INCLUDED
#define PROTOBUF_OfflineReward_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
// @@protoc_insertion_point(includes)

namespace com {
namespace road {
namespace yishi {
namespace proto {
namespace player {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_OfflineReward_2eproto();
void protobuf_AssignDesc_OfflineReward_2eproto();
void protobuf_ShutdownFile_OfflineReward_2eproto();

class OfflineRewardMsg;

// ===================================================================

class OfflineRewardMsg : public ::google::protobuf::MessageLite {
 public:
  OfflineRewardMsg();
  virtual ~OfflineRewardMsg();

  OfflineRewardMsg(const OfflineRewardMsg& from);

  inline OfflineRewardMsg& operator=(const OfflineRewardMsg& from) {
    CopyFrom(from);
    return *this;
  }

  static const OfflineRewardMsg& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const OfflineRewardMsg* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(OfflineRewardMsg* other);

  // implements Message ----------------------------------------------

  OfflineRewardMsg* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const OfflineRewardMsg& from);
  void MergeFrom(const OfflineRewardMsg& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 offline_time = 1;
  inline bool has_offline_time() const;
  inline void clear_offline_time();
  static const int kOfflineTimeFieldNumber = 1;
  inline ::google::protobuf::int32 offline_time() const;
  inline void set_offline_time(::google::protobuf::int32 value);

  // optional int32 gp_count = 2;
  inline bool has_gp_count() const;
  inline void clear_gp_count();
  static const int kGpCountFieldNumber = 2;
  inline ::google::protobuf::int32 gp_count() const;
  inline void set_gp_count(::google::protobuf::int32 value);

  // optional int32 rate_count = 3;
  inline bool has_rate_count() const;
  inline void clear_rate_count();
  static const int kRateCountFieldNumber = 3;
  inline ::google::protobuf::int32 rate_count() const;
  inline void set_rate_count(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:com.road.yishi.proto.player.OfflineRewardMsg)
 private:
  inline void set_has_offline_time();
  inline void clear_has_offline_time();
  inline void set_has_gp_count();
  inline void clear_has_gp_count();
  inline void set_has_rate_count();
  inline void clear_has_rate_count();

  ::google::protobuf::int32 offline_time_;
  ::google::protobuf::int32 gp_count_;
  ::google::protobuf::int32 rate_count_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_OfflineReward_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_OfflineReward_2eproto();
  #endif
  friend void protobuf_AssignDesc_OfflineReward_2eproto();
  friend void protobuf_ShutdownFile_OfflineReward_2eproto();

  void InitAsDefaultInstance();
  static OfflineRewardMsg* default_instance_;
};
// ===================================================================


// ===================================================================

// OfflineRewardMsg

// optional int32 offline_time = 1;
inline bool OfflineRewardMsg::has_offline_time() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void OfflineRewardMsg::set_has_offline_time() {
  _has_bits_[0] |= 0x00000001u;
}
inline void OfflineRewardMsg::clear_has_offline_time() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void OfflineRewardMsg::clear_offline_time() {
  offline_time_ = 0;
  clear_has_offline_time();
}
inline ::google::protobuf::int32 OfflineRewardMsg::offline_time() const {
  return offline_time_;
}
inline void OfflineRewardMsg::set_offline_time(::google::protobuf::int32 value) {
  set_has_offline_time();
  offline_time_ = value;
}

// optional int32 gp_count = 2;
inline bool OfflineRewardMsg::has_gp_count() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void OfflineRewardMsg::set_has_gp_count() {
  _has_bits_[0] |= 0x00000002u;
}
inline void OfflineRewardMsg::clear_has_gp_count() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void OfflineRewardMsg::clear_gp_count() {
  gp_count_ = 0;
  clear_has_gp_count();
}
inline ::google::protobuf::int32 OfflineRewardMsg::gp_count() const {
  return gp_count_;
}
inline void OfflineRewardMsg::set_gp_count(::google::protobuf::int32 value) {
  set_has_gp_count();
  gp_count_ = value;
}

// optional int32 rate_count = 3;
inline bool OfflineRewardMsg::has_rate_count() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void OfflineRewardMsg::set_has_rate_count() {
  _has_bits_[0] |= 0x00000004u;
}
inline void OfflineRewardMsg::clear_has_rate_count() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void OfflineRewardMsg::clear_rate_count() {
  rate_count_ = 0;
  clear_has_rate_count();
}
inline ::google::protobuf::int32 OfflineRewardMsg::rate_count() const {
  return rate_count_;
}
inline void OfflineRewardMsg::set_rate_count(::google::protobuf::int32 value) {
  set_has_rate_count();
  rate_count_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace player
}  // namespace proto
}  // namespace yishi
}  // namespace road
}  // namespace com

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_OfflineReward_2eproto__INCLUDED
