// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PayType.proto

#ifndef PROTOBUF_PayType_2eproto__INCLUDED
#define PROTOBUF_PayType_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
// @@protoc_insertion_point(includes)

namespace com {
namespace road {
namespace yishi {
namespace proto {
namespace player {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_PayType_2eproto();
void protobuf_AssignDesc_PayType_2eproto();
void protobuf_ShutdownFile_PayType_2eproto();

class PayTypeMsg;

// ===================================================================

class PayTypeMsg : public ::google::protobuf::MessageLite {
 public:
  PayTypeMsg();
  virtual ~PayTypeMsg();

  PayTypeMsg(const PayTypeMsg& from);

  inline PayTypeMsg& operator=(const PayTypeMsg& from) {
    CopyFrom(from);
    return *this;
  }

  static const PayTypeMsg& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const PayTypeMsg* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(PayTypeMsg* other);

  // implements Message ----------------------------------------------

  PayTypeMsg* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const PayTypeMsg& from);
  void MergeFrom(const PayTypeMsg& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 pay_type = 1;
  inline bool has_pay_type() const;
  inline void clear_pay_type();
  static const int kPayTypeFieldNumber = 1;
  inline ::google::protobuf::int32 pay_type() const;
  inline void set_pay_type(::google::protobuf::int32 value);

  // optional int32 property1 = 2;
  inline bool has_property1() const;
  inline void clear_property1();
  static const int kProperty1FieldNumber = 2;
  inline ::google::protobuf::int32 property1() const;
  inline void set_property1(::google::protobuf::int32 value);

  // optional int32 property2 = 3;
  inline bool has_property2() const;
  inline void clear_property2();
  static const int kProperty2FieldNumber = 3;
  inline ::google::protobuf::int32 property2() const;
  inline void set_property2(::google::protobuf::int32 value);

  // optional int32 type = 4;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 4;
  inline ::google::protobuf::int32 type() const;
  inline void set_type(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:com.road.yishi.proto.player.PayTypeMsg)
 private:
  inline void set_has_pay_type();
  inline void clear_has_pay_type();
  inline void set_has_property1();
  inline void clear_has_property1();
  inline void set_has_property2();
  inline void clear_has_property2();
  inline void set_has_type();
  inline void clear_has_type();

  ::google::protobuf::int32 pay_type_;
  ::google::protobuf::int32 property1_;
  ::google::protobuf::int32 property2_;
  ::google::protobuf::int32 type_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_PayType_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_PayType_2eproto();
  #endif
  friend void protobuf_AssignDesc_PayType_2eproto();
  friend void protobuf_ShutdownFile_PayType_2eproto();

  void InitAsDefaultInstance();
  static PayTypeMsg* default_instance_;
};
// ===================================================================


// ===================================================================

// PayTypeMsg

// optional int32 pay_type = 1;
inline bool PayTypeMsg::has_pay_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PayTypeMsg::set_has_pay_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PayTypeMsg::clear_has_pay_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PayTypeMsg::clear_pay_type() {
  pay_type_ = 0;
  clear_has_pay_type();
}
inline ::google::protobuf::int32 PayTypeMsg::pay_type() const {
  return pay_type_;
}
inline void PayTypeMsg::set_pay_type(::google::protobuf::int32 value) {
  set_has_pay_type();
  pay_type_ = value;
}

// optional int32 property1 = 2;
inline bool PayTypeMsg::has_property1() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void PayTypeMsg::set_has_property1() {
  _has_bits_[0] |= 0x00000002u;
}
inline void PayTypeMsg::clear_has_property1() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void PayTypeMsg::clear_property1() {
  property1_ = 0;
  clear_has_property1();
}
inline ::google::protobuf::int32 PayTypeMsg::property1() const {
  return property1_;
}
inline void PayTypeMsg::set_property1(::google::protobuf::int32 value) {
  set_has_property1();
  property1_ = value;
}

// optional int32 property2 = 3;
inline bool PayTypeMsg::has_property2() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void PayTypeMsg::set_has_property2() {
  _has_bits_[0] |= 0x00000004u;
}
inline void PayTypeMsg::clear_has_property2() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void PayTypeMsg::clear_property2() {
  property2_ = 0;
  clear_has_property2();
}
inline ::google::protobuf::int32 PayTypeMsg::property2() const {
  return property2_;
}
inline void PayTypeMsg::set_property2(::google::protobuf::int32 value) {
  set_has_property2();
  property2_ = value;
}

// optional int32 type = 4;
inline bool PayTypeMsg::has_type() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void PayTypeMsg::set_has_type() {
  _has_bits_[0] |= 0x00000008u;
}
inline void PayTypeMsg::clear_has_type() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void PayTypeMsg::clear_type() {
  type_ = 0;
  clear_has_type();
}
inline ::google::protobuf::int32 PayTypeMsg::type() const {
  return type_;
}
inline void PayTypeMsg::set_type(::google::protobuf::int32 value) {
  set_has_type();
  type_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace player
}  // namespace proto
}  // namespace yishi
}  // namespace road
}  // namespace com

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_PayType_2eproto__INCLUDED
