// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PlayerSignRsp.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "PlayerSignRsp.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
// @@protoc_insertion_point(includes)

namespace com {
namespace road {
namespace yishi {
namespace proto {
namespace player {

void protobuf_ShutdownFile_PlayerSignRsp_2eproto() {
  delete PlayerSignRspMsg::default_instance_;
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
void protobuf_AddDesc_PlayerSignRsp_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#else
void protobuf_AddDesc_PlayerSignRsp_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#endif
  PlayerSignRspMsg::default_instance_ = new PlayerSignRspMsg();
  PlayerSignRspMsg::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_PlayerSignRsp_2eproto);
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_PlayerSignRsp_2eproto_once_);
void protobuf_AddDesc_PlayerSignRsp_2eproto() {
  ::google::protobuf::::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_PlayerSignRsp_2eproto_once_,
                 &protobuf_AddDesc_PlayerSignRsp_2eproto_impl);
}
#else
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_PlayerSignRsp_2eproto {
  StaticDescriptorInitializer_PlayerSignRsp_2eproto() {
    protobuf_AddDesc_PlayerSignRsp_2eproto();
  }
} static_descriptor_initializer_PlayerSignRsp_2eproto_;
#endif

// ===================================================================

#ifndef _MSC_VER
const int PlayerSignRspMsg::kSignDateFieldNumber;
const int PlayerSignRspMsg::kSignTimesFieldNumber;
const int PlayerSignRspMsg::kSignSiteFieldNumber;
#endif  // !_MSC_VER

PlayerSignRspMsg::PlayerSignRspMsg()
  : ::google::protobuf::MessageLite() {
  SharedCtor();
}

void PlayerSignRspMsg::InitAsDefaultInstance() {
}

PlayerSignRspMsg::PlayerSignRspMsg(const PlayerSignRspMsg& from)
  : ::google::protobuf::MessageLite() {
  SharedCtor();
  MergeFrom(from);
}

void PlayerSignRspMsg::SharedCtor() {
  _cached_size_ = 0;
  signdate_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  signtimes_ = 0;
  signsite_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

PlayerSignRspMsg::~PlayerSignRspMsg() {
  SharedDtor();
}

void PlayerSignRspMsg::SharedDtor() {
  if (signdate_ != &::google::protobuf::internal::kEmptyString) {
    delete signdate_;
  }
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
  }
}

void PlayerSignRspMsg::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const PlayerSignRspMsg& PlayerSignRspMsg::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_PlayerSignRsp_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_PlayerSignRsp_2eproto();
#endif
  return *default_instance_;
}

PlayerSignRspMsg* PlayerSignRspMsg::default_instance_ = NULL;

PlayerSignRspMsg* PlayerSignRspMsg::New() const {
  return new PlayerSignRspMsg;
}

void PlayerSignRspMsg::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_signdate()) {
      if (signdate_ != &::google::protobuf::internal::kEmptyString) {
        signdate_->clear();
      }
    }
    signtimes_ = 0;
    signsite_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

bool PlayerSignRspMsg::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string signDate = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_signdate()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_signTimes;
        break;
      }

      // optional int32 signTimes = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_signTimes:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &signtimes_)));
          set_has_signtimes();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(32)) goto parse_signSite;
        break;
      }

      // optional int32 signSite = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_signSite:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &signsite_)));
          set_has_signsite();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void PlayerSignRspMsg::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional string signDate = 1;
  if (has_signdate()) {
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->signdate(), output);
  }

  // optional int32 signTimes = 2;
  if (has_signtimes()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->signtimes(), output);
  }

  // optional int32 signSite = 4;
  if (has_signsite()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->signsite(), output);
  }

}

int PlayerSignRspMsg::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional string signDate = 1;
    if (has_signdate()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->signdate());
    }

    // optional int32 signTimes = 2;
    if (has_signtimes()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->signtimes());
    }

    // optional int32 signSite = 4;
    if (has_signsite()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->signsite());
    }

  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PlayerSignRspMsg::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const PlayerSignRspMsg*>(&from));
}

void PlayerSignRspMsg::MergeFrom(const PlayerSignRspMsg& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_signdate()) {
      set_signdate(from.signdate());
    }
    if (from.has_signtimes()) {
      set_signtimes(from.signtimes());
    }
    if (from.has_signsite()) {
      set_signsite(from.signsite());
    }
  }
}

void PlayerSignRspMsg::CopyFrom(const PlayerSignRspMsg& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PlayerSignRspMsg::IsInitialized() const {

  return true;
}

void PlayerSignRspMsg::Swap(PlayerSignRspMsg* other) {
  if (other != this) {
    std::swap(signdate_, other->signdate_);
    std::swap(signtimes_, other->signtimes_);
    std::swap(signsite_, other->signsite_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::std::string PlayerSignRspMsg::GetTypeName() const {
  return "com.road.yishi.proto.player.PlayerSignRspMsg";
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace player
}  // namespace proto
}  // namespace yishi
}  // namespace road
}  // namespace com

// @@protoc_insertion_point(global_scope)
