// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PlayerActiveReq.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "PlayerActiveReq.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
// @@protoc_insertion_point(includes)

namespace com {
namespace road {
namespace yishi {
namespace proto {
namespace player {

void protobuf_ShutdownFile_PlayerActiveReq_2eproto() {
  delete PlayerActiveReqMsg::default_instance_;
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
void protobuf_AddDesc_PlayerActiveReq_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#else
void protobuf_AddDesc_PlayerActiveReq_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#endif
  PlayerActiveReqMsg::default_instance_ = new PlayerActiveReqMsg();
  PlayerActiveReqMsg::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_PlayerActiveReq_2eproto);
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_PlayerActiveReq_2eproto_once_);
void protobuf_AddDesc_PlayerActiveReq_2eproto() {
  ::google::protobuf::::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_PlayerActiveReq_2eproto_once_,
                 &protobuf_AddDesc_PlayerActiveReq_2eproto_impl);
}
#else
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_PlayerActiveReq_2eproto {
  StaticDescriptorInitializer_PlayerActiveReq_2eproto() {
    protobuf_AddDesc_PlayerActiveReq_2eproto();
  }
} static_descriptor_initializer_PlayerActiveReq_2eproto_;
#endif

// ===================================================================

#ifndef _MSC_VER
const int PlayerActiveReqMsg::kKeyFieldNumber;
const int PlayerActiveReqMsg::kActiveIdFieldNumber;
#endif  // !_MSC_VER

PlayerActiveReqMsg::PlayerActiveReqMsg()
  : ::google::protobuf::MessageLite() {
  SharedCtor();
}

void PlayerActiveReqMsg::InitAsDefaultInstance() {
}

PlayerActiveReqMsg::PlayerActiveReqMsg(const PlayerActiveReqMsg& from)
  : ::google::protobuf::MessageLite() {
  SharedCtor();
  MergeFrom(from);
}

void PlayerActiveReqMsg::SharedCtor() {
  _cached_size_ = 0;
  key_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  activeid_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

PlayerActiveReqMsg::~PlayerActiveReqMsg() {
  SharedDtor();
}

void PlayerActiveReqMsg::SharedDtor() {
  if (key_ != &::google::protobuf::internal::kEmptyString) {
    delete key_;
  }
  if (activeid_ != &::google::protobuf::internal::kEmptyString) {
    delete activeid_;
  }
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
  }
}

void PlayerActiveReqMsg::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const PlayerActiveReqMsg& PlayerActiveReqMsg::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_PlayerActiveReq_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_PlayerActiveReq_2eproto();
#endif
  return *default_instance_;
}

PlayerActiveReqMsg* PlayerActiveReqMsg::default_instance_ = NULL;

PlayerActiveReqMsg* PlayerActiveReqMsg::New() const {
  return new PlayerActiveReqMsg;
}

void PlayerActiveReqMsg::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_key()) {
      if (key_ != &::google::protobuf::internal::kEmptyString) {
        key_->clear();
      }
    }
    if (has_activeid()) {
      if (activeid_ != &::google::protobuf::internal::kEmptyString) {
        activeid_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

bool PlayerActiveReqMsg::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string key = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_key()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_activeId;
        break;
      }

      // optional string activeId = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_activeId:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_activeid()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void PlayerActiveReqMsg::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional string key = 1;
  if (has_key()) {
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->key(), output);
  }

  // optional string activeId = 2;
  if (has_activeid()) {
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->activeid(), output);
  }

}

int PlayerActiveReqMsg::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional string key = 1;
    if (has_key()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->key());
    }

    // optional string activeId = 2;
    if (has_activeid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->activeid());
    }

  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PlayerActiveReqMsg::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const PlayerActiveReqMsg*>(&from));
}

void PlayerActiveReqMsg::MergeFrom(const PlayerActiveReqMsg& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_key()) {
      set_key(from.key());
    }
    if (from.has_activeid()) {
      set_activeid(from.activeid());
    }
  }
}

void PlayerActiveReqMsg::CopyFrom(const PlayerActiveReqMsg& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PlayerActiveReqMsg::IsInitialized() const {

  return true;
}

void PlayerActiveReqMsg::Swap(PlayerActiveReqMsg* other) {
  if (other != this) {
    std::swap(key_, other->key_);
    std::swap(activeid_, other->activeid_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::std::string PlayerActiveReqMsg::GetTypeName() const {
  return "com.road.yishi.proto.player.PlayerActiveReqMsg";
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace player
}  // namespace proto
}  // namespace yishi
}  // namespace road
}  // namespace com

// @@protoc_insertion_point(global_scope)
