// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PlayerCheck.proto

#ifndef PROTOBUF_PlayerCheck_2eproto__INCLUDED
#define PROTOBUF_PlayerCheck_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
// @@protoc_insertion_point(includes)

namespace com {
namespace road {
namespace yishi {
namespace proto {
namespace player {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_PlayerCheck_2eproto();
void protobuf_AssignDesc_PlayerCheck_2eproto();
void protobuf_ShutdownFile_PlayerCheck_2eproto();

class PlayerCheckMsg;

// ===================================================================

class PlayerCheckMsg : public ::google::protobuf::MessageLite {
 public:
  PlayerCheckMsg();
  virtual ~PlayerCheckMsg();

  PlayerCheckMsg(const PlayerCheckMsg& from);

  inline PlayerCheckMsg& operator=(const PlayerCheckMsg& from) {
    CopyFrom(from);
    return *this;
  }

  static const PlayerCheckMsg& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const PlayerCheckMsg* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(PlayerCheckMsg* other);

  // implements Message ----------------------------------------------

  PlayerCheckMsg* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const PlayerCheckMsg& from);
  void MergeFrom(const PlayerCheckMsg& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 player_id = 1;
  inline bool has_player_id() const;
  inline void clear_player_id();
  static const int kPlayerIdFieldNumber = 1;
  inline ::google::protobuf::int32 player_id() const;
  inline void set_player_id(::google::protobuf::int32 value);

  // optional string key = 2;
  inline bool has_key() const;
  inline void clear_key();
  static const int kKeyFieldNumber = 2;
  inline const ::std::string& key() const;
  inline void set_key(const ::std::string& value);
  inline void set_key(const char* value);
  inline void set_key(const char* value, size_t size);
  inline ::std::string* mutable_key();
  inline ::std::string* release_key();
  inline void set_allocated_key(::std::string* key);

  // optional bool result = 3;
  inline bool has_result() const;
  inline void clear_result();
  static const int kResultFieldNumber = 3;
  inline bool result() const;
  inline void set_result(bool value);

  // @@protoc_insertion_point(class_scope:com.road.yishi.proto.player.PlayerCheckMsg)
 private:
  inline void set_has_player_id();
  inline void clear_has_player_id();
  inline void set_has_key();
  inline void clear_has_key();
  inline void set_has_result();
  inline void clear_has_result();

  ::std::string* key_;
  ::google::protobuf::int32 player_id_;
  bool result_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_PlayerCheck_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_PlayerCheck_2eproto();
  #endif
  friend void protobuf_AssignDesc_PlayerCheck_2eproto();
  friend void protobuf_ShutdownFile_PlayerCheck_2eproto();

  void InitAsDefaultInstance();
  static PlayerCheckMsg* default_instance_;
};
// ===================================================================


// ===================================================================

// PlayerCheckMsg

// optional int32 player_id = 1;
inline bool PlayerCheckMsg::has_player_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PlayerCheckMsg::set_has_player_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PlayerCheckMsg::clear_has_player_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PlayerCheckMsg::clear_player_id() {
  player_id_ = 0;
  clear_has_player_id();
}
inline ::google::protobuf::int32 PlayerCheckMsg::player_id() const {
  return player_id_;
}
inline void PlayerCheckMsg::set_player_id(::google::protobuf::int32 value) {
  set_has_player_id();
  player_id_ = value;
}

// optional string key = 2;
inline bool PlayerCheckMsg::has_key() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void PlayerCheckMsg::set_has_key() {
  _has_bits_[0] |= 0x00000002u;
}
inline void PlayerCheckMsg::clear_has_key() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void PlayerCheckMsg::clear_key() {
  if (key_ != &::google::protobuf::internal::kEmptyString) {
    key_->clear();
  }
  clear_has_key();
}
inline const ::std::string& PlayerCheckMsg::key() const {
  return *key_;
}
inline void PlayerCheckMsg::set_key(const ::std::string& value) {
  set_has_key();
  if (key_ == &::google::protobuf::internal::kEmptyString) {
    key_ = new ::std::string;
  }
  key_->assign(value);
}
inline void PlayerCheckMsg::set_key(const char* value) {
  set_has_key();
  if (key_ == &::google::protobuf::internal::kEmptyString) {
    key_ = new ::std::string;
  }
  key_->assign(value);
}
inline void PlayerCheckMsg::set_key(const char* value, size_t size) {
  set_has_key();
  if (key_ == &::google::protobuf::internal::kEmptyString) {
    key_ = new ::std::string;
  }
  key_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* PlayerCheckMsg::mutable_key() {
  set_has_key();
  if (key_ == &::google::protobuf::internal::kEmptyString) {
    key_ = new ::std::string;
  }
  return key_;
}
inline ::std::string* PlayerCheckMsg::release_key() {
  clear_has_key();
  if (key_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = key_;
    key_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void PlayerCheckMsg::set_allocated_key(::std::string* key) {
  if (key_ != &::google::protobuf::internal::kEmptyString) {
    delete key_;
  }
  if (key) {
    set_has_key();
    key_ = key;
  } else {
    clear_has_key();
    key_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional bool result = 3;
inline bool PlayerCheckMsg::has_result() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void PlayerCheckMsg::set_has_result() {
  _has_bits_[0] |= 0x00000004u;
}
inline void PlayerCheckMsg::clear_has_result() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void PlayerCheckMsg::clear_result() {
  result_ = false;
  clear_has_result();
}
inline bool PlayerCheckMsg::result() const {
  return result_;
}
inline void PlayerCheckMsg::set_result(bool value) {
  set_has_result();
  result_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace player
}  // namespace proto
}  // namespace yishi
}  // namespace road
}  // namespace com

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_PlayerCheck_2eproto__INCLUDED
