// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PropertyUpdated.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "PropertyUpdated.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
// @@protoc_insertion_point(includes)

namespace com {
namespace road {
namespace yishi {
namespace proto {
namespace player {

void protobuf_ShutdownFile_PropertyUpdated_2eproto() {
  delete PropertyUpdatedMsg::default_instance_;
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
void protobuf_AddDesc_PropertyUpdated_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#else
void protobuf_AddDesc_PropertyUpdated_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#endif
  PropertyUpdatedMsg::default_instance_ = new PropertyUpdatedMsg();
  PropertyUpdatedMsg::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_PropertyUpdated_2eproto);
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_PropertyUpdated_2eproto_once_);
void protobuf_AddDesc_PropertyUpdated_2eproto() {
  ::google::protobuf::::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_PropertyUpdated_2eproto_once_,
                 &protobuf_AddDesc_PropertyUpdated_2eproto_impl);
}
#else
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_PropertyUpdated_2eproto {
  StaticDescriptorInitializer_PropertyUpdated_2eproto() {
    protobuf_AddDesc_PropertyUpdated_2eproto();
  }
} static_descriptor_initializer_PropertyUpdated_2eproto_;
#endif

// ===================================================================

#ifndef _MSC_VER
const int PropertyUpdatedMsg::kPropertyTypeFieldNumber;
const int PropertyUpdatedMsg::kValueFieldNumber;
#endif  // !_MSC_VER

PropertyUpdatedMsg::PropertyUpdatedMsg()
  : ::google::protobuf::MessageLite() {
  SharedCtor();
}

void PropertyUpdatedMsg::InitAsDefaultInstance() {
}

PropertyUpdatedMsg::PropertyUpdatedMsg(const PropertyUpdatedMsg& from)
  : ::google::protobuf::MessageLite() {
  SharedCtor();
  MergeFrom(from);
}

void PropertyUpdatedMsg::SharedCtor() {
  _cached_size_ = 0;
  property_type_ = 0;
  value_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

PropertyUpdatedMsg::~PropertyUpdatedMsg() {
  SharedDtor();
}

void PropertyUpdatedMsg::SharedDtor() {
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
  }
}

void PropertyUpdatedMsg::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const PropertyUpdatedMsg& PropertyUpdatedMsg::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_PropertyUpdated_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_PropertyUpdated_2eproto();
#endif
  return *default_instance_;
}

PropertyUpdatedMsg* PropertyUpdatedMsg::default_instance_ = NULL;

PropertyUpdatedMsg* PropertyUpdatedMsg::New() const {
  return new PropertyUpdatedMsg;
}

void PropertyUpdatedMsg::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    property_type_ = 0;
    value_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

bool PropertyUpdatedMsg::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 property_type = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &property_type_)));
          set_has_property_type();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_value;
        break;
      }

      // optional int32 value = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_value:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &value_)));
          set_has_value();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void PropertyUpdatedMsg::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional int32 property_type = 1;
  if (has_property_type()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->property_type(), output);
  }

  // optional int32 value = 2;
  if (has_value()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->value(), output);
  }

}

int PropertyUpdatedMsg::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional int32 property_type = 1;
    if (has_property_type()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->property_type());
    }

    // optional int32 value = 2;
    if (has_value()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->value());
    }

  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PropertyUpdatedMsg::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const PropertyUpdatedMsg*>(&from));
}

void PropertyUpdatedMsg::MergeFrom(const PropertyUpdatedMsg& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_property_type()) {
      set_property_type(from.property_type());
    }
    if (from.has_value()) {
      set_value(from.value());
    }
  }
}

void PropertyUpdatedMsg::CopyFrom(const PropertyUpdatedMsg& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PropertyUpdatedMsg::IsInitialized() const {

  return true;
}

void PropertyUpdatedMsg::Swap(PropertyUpdatedMsg* other) {
  if (other != this) {
    std::swap(property_type_, other->property_type_);
    std::swap(value_, other->value_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::std::string PropertyUpdatedMsg::GetTypeName() const {
  return "com.road.yishi.proto.player.PropertyUpdatedMsg";
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace player
}  // namespace proto
}  // namespace yishi
}  // namespace road
}  // namespace com

// @@protoc_insertion_point(global_scope)
