// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PropertyUpdated.proto

#ifndef PROTOBUF_PropertyUpdated_2eproto__INCLUDED
#define PROTOBUF_PropertyUpdated_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
// @@protoc_insertion_point(includes)

namespace com {
namespace road {
namespace yishi {
namespace proto {
namespace player {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_PropertyUpdated_2eproto();
void protobuf_AssignDesc_PropertyUpdated_2eproto();
void protobuf_ShutdownFile_PropertyUpdated_2eproto();

class PropertyUpdatedMsg;

// ===================================================================

class PropertyUpdatedMsg : public ::google::protobuf::MessageLite {
 public:
  PropertyUpdatedMsg();
  virtual ~PropertyUpdatedMsg();

  PropertyUpdatedMsg(const PropertyUpdatedMsg& from);

  inline PropertyUpdatedMsg& operator=(const PropertyUpdatedMsg& from) {
    CopyFrom(from);
    return *this;
  }

  static const PropertyUpdatedMsg& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const PropertyUpdatedMsg* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(PropertyUpdatedMsg* other);

  // implements Message ----------------------------------------------

  PropertyUpdatedMsg* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const PropertyUpdatedMsg& from);
  void MergeFrom(const PropertyUpdatedMsg& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 property_type = 1;
  inline bool has_property_type() const;
  inline void clear_property_type();
  static const int kPropertyTypeFieldNumber = 1;
  inline ::google::protobuf::int32 property_type() const;
  inline void set_property_type(::google::protobuf::int32 value);

  // optional int32 value = 2;
  inline bool has_value() const;
  inline void clear_value();
  static const int kValueFieldNumber = 2;
  inline ::google::protobuf::int32 value() const;
  inline void set_value(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:com.road.yishi.proto.player.PropertyUpdatedMsg)
 private:
  inline void set_has_property_type();
  inline void clear_has_property_type();
  inline void set_has_value();
  inline void clear_has_value();

  ::google::protobuf::int32 property_type_;
  ::google::protobuf::int32 value_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_PropertyUpdated_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_PropertyUpdated_2eproto();
  #endif
  friend void protobuf_AssignDesc_PropertyUpdated_2eproto();
  friend void protobuf_ShutdownFile_PropertyUpdated_2eproto();

  void InitAsDefaultInstance();
  static PropertyUpdatedMsg* default_instance_;
};
// ===================================================================


// ===================================================================

// PropertyUpdatedMsg

// optional int32 property_type = 1;
inline bool PropertyUpdatedMsg::has_property_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PropertyUpdatedMsg::set_has_property_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PropertyUpdatedMsg::clear_has_property_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PropertyUpdatedMsg::clear_property_type() {
  property_type_ = 0;
  clear_has_property_type();
}
inline ::google::protobuf::int32 PropertyUpdatedMsg::property_type() const {
  return property_type_;
}
inline void PropertyUpdatedMsg::set_property_type(::google::protobuf::int32 value) {
  set_has_property_type();
  property_type_ = value;
}

// optional int32 value = 2;
inline bool PropertyUpdatedMsg::has_value() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void PropertyUpdatedMsg::set_has_value() {
  _has_bits_[0] |= 0x00000002u;
}
inline void PropertyUpdatedMsg::clear_has_value() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void PropertyUpdatedMsg::clear_value() {
  value_ = 0;
  clear_has_value();
}
inline ::google::protobuf::int32 PropertyUpdatedMsg::value() const {
  return value_;
}
inline void PropertyUpdatedMsg::set_value(::google::protobuf::int32 value) {
  set_has_value();
  value_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace player
}  // namespace proto
}  // namespace yishi
}  // namespace road
}  // namespace com

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_PropertyUpdated_2eproto__INCLUDED
