// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SynchronizedTimeMsgProto.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "SynchronizedTimeMsgProto.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
// @@protoc_insertion_point(includes)

namespace com {
namespace road {
namespace yishi {
namespace proto {
namespace player {

void protobuf_ShutdownFile_SynchronizedTimeMsgProto_2eproto() {
  delete SynchronizedTimeMsg::default_instance_;
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
void protobuf_AddDesc_SynchronizedTimeMsgProto_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#else
void protobuf_AddDesc_SynchronizedTimeMsgProto_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#endif
  SynchronizedTimeMsg::default_instance_ = new SynchronizedTimeMsg();
  SynchronizedTimeMsg::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_SynchronizedTimeMsgProto_2eproto);
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_SynchronizedTimeMsgProto_2eproto_once_);
void protobuf_AddDesc_SynchronizedTimeMsgProto_2eproto() {
  ::google::protobuf::::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_SynchronizedTimeMsgProto_2eproto_once_,
                 &protobuf_AddDesc_SynchronizedTimeMsgProto_2eproto_impl);
}
#else
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_SynchronizedTimeMsgProto_2eproto {
  StaticDescriptorInitializer_SynchronizedTimeMsgProto_2eproto() {
    protobuf_AddDesc_SynchronizedTimeMsgProto_2eproto();
  }
} static_descriptor_initializer_SynchronizedTimeMsgProto_2eproto_;
#endif

// ===================================================================

#ifndef _MSC_VER
const int SynchronizedTimeMsg::kSysCurtimeFieldNumber;
#endif  // !_MSC_VER

SynchronizedTimeMsg::SynchronizedTimeMsg()
  : ::google::protobuf::MessageLite() {
  SharedCtor();
}

void SynchronizedTimeMsg::InitAsDefaultInstance() {
}

SynchronizedTimeMsg::SynchronizedTimeMsg(const SynchronizedTimeMsg& from)
  : ::google::protobuf::MessageLite() {
  SharedCtor();
  MergeFrom(from);
}

void SynchronizedTimeMsg::SharedCtor() {
  _cached_size_ = 0;
  sys_curtime_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

SynchronizedTimeMsg::~SynchronizedTimeMsg() {
  SharedDtor();
}

void SynchronizedTimeMsg::SharedDtor() {
  if (sys_curtime_ != &::google::protobuf::internal::kEmptyString) {
    delete sys_curtime_;
  }
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
  }
}

void SynchronizedTimeMsg::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const SynchronizedTimeMsg& SynchronizedTimeMsg::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_SynchronizedTimeMsgProto_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_SynchronizedTimeMsgProto_2eproto();
#endif
  return *default_instance_;
}

SynchronizedTimeMsg* SynchronizedTimeMsg::default_instance_ = NULL;

SynchronizedTimeMsg* SynchronizedTimeMsg::New() const {
  return new SynchronizedTimeMsg;
}

void SynchronizedTimeMsg::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_sys_curtime()) {
      if (sys_curtime_ != &::google::protobuf::internal::kEmptyString) {
        sys_curtime_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

bool SynchronizedTimeMsg::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string sys_curtime = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_sys_curtime()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void SynchronizedTimeMsg::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional string sys_curtime = 1;
  if (has_sys_curtime()) {
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->sys_curtime(), output);
  }

}

int SynchronizedTimeMsg::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional string sys_curtime = 1;
    if (has_sys_curtime()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->sys_curtime());
    }

  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SynchronizedTimeMsg::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const SynchronizedTimeMsg*>(&from));
}

void SynchronizedTimeMsg::MergeFrom(const SynchronizedTimeMsg& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_sys_curtime()) {
      set_sys_curtime(from.sys_curtime());
    }
  }
}

void SynchronizedTimeMsg::CopyFrom(const SynchronizedTimeMsg& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SynchronizedTimeMsg::IsInitialized() const {

  return true;
}

void SynchronizedTimeMsg::Swap(SynchronizedTimeMsg* other) {
  if (other != this) {
    std::swap(sys_curtime_, other->sys_curtime_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::std::string SynchronizedTimeMsg::GetTypeName() const {
  return "com.road.yishi.proto.player.SynchronizedTimeMsg";
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace player
}  // namespace proto
}  // namespace yishi
}  // namespace road
}  // namespace com

// @@protoc_insertion_point(global_scope)
