// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SystemPropertyMsg.proto

#ifndef PROTOBUF_SystemPropertyMsg_2eproto__INCLUDED
#define PROTOBUF_SystemPropertyMsg_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
// @@protoc_insertion_point(includes)

namespace com {
namespace road {
namespace yishi {
namespace proto {
namespace player {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_SystemPropertyMsg_2eproto();
void protobuf_AssignDesc_SystemPropertyMsg_2eproto();
void protobuf_ShutdownFile_SystemPropertyMsg_2eproto();

class SystemPropertyMsg;

// ===================================================================

class SystemPropertyMsg : public ::google::protobuf::MessageLite {
 public:
  SystemPropertyMsg();
  virtual ~SystemPropertyMsg();

  SystemPropertyMsg(const SystemPropertyMsg& from);

  inline SystemPropertyMsg& operator=(const SystemPropertyMsg& from) {
    CopyFrom(from);
    return *this;
  }

  static const SystemPropertyMsg& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const SystemPropertyMsg* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(SystemPropertyMsg* other);

  // implements Message ----------------------------------------------

  SystemPropertyMsg* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const SystemPropertyMsg& from);
  void MergeFrom(const SystemPropertyMsg& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string sys_curtime = 1;
  inline bool has_sys_curtime() const;
  inline void clear_sys_curtime();
  static const int kSysCurtimeFieldNumber = 1;
  inline const ::std::string& sys_curtime() const;
  inline void set_sys_curtime(const ::std::string& value);
  inline void set_sys_curtime(const char* value);
  inline void set_sys_curtime(const char* value, size_t size);
  inline ::std::string* mutable_sys_curtime();
  inline ::std::string* release_sys_curtime();
  inline void set_allocated_sys_curtime(::std::string* sys_curtime);

  // optional string sys_starTime = 2;
  inline bool has_sys_startime() const;
  inline void clear_sys_startime();
  static const int kSysStarTimeFieldNumber = 2;
  inline const ::std::string& sys_startime() const;
  inline void set_sys_startime(const ::std::string& value);
  inline void set_sys_startime(const char* value);
  inline void set_sys_startime(const char* value, size_t size);
  inline ::std::string* mutable_sys_startime();
  inline ::std::string* release_sys_startime();
  inline void set_allocated_sys_startime(::std::string* sys_startime);

  // @@protoc_insertion_point(class_scope:com.road.yishi.proto.player.SystemPropertyMsg)
 private:
  inline void set_has_sys_curtime();
  inline void clear_has_sys_curtime();
  inline void set_has_sys_startime();
  inline void clear_has_sys_startime();

  ::std::string* sys_curtime_;
  ::std::string* sys_startime_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_SystemPropertyMsg_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_SystemPropertyMsg_2eproto();
  #endif
  friend void protobuf_AssignDesc_SystemPropertyMsg_2eproto();
  friend void protobuf_ShutdownFile_SystemPropertyMsg_2eproto();

  void InitAsDefaultInstance();
  static SystemPropertyMsg* default_instance_;
};
// ===================================================================


// ===================================================================

// SystemPropertyMsg

// optional string sys_curtime = 1;
inline bool SystemPropertyMsg::has_sys_curtime() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SystemPropertyMsg::set_has_sys_curtime() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SystemPropertyMsg::clear_has_sys_curtime() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SystemPropertyMsg::clear_sys_curtime() {
  if (sys_curtime_ != &::google::protobuf::internal::kEmptyString) {
    sys_curtime_->clear();
  }
  clear_has_sys_curtime();
}
inline const ::std::string& SystemPropertyMsg::sys_curtime() const {
  return *sys_curtime_;
}
inline void SystemPropertyMsg::set_sys_curtime(const ::std::string& value) {
  set_has_sys_curtime();
  if (sys_curtime_ == &::google::protobuf::internal::kEmptyString) {
    sys_curtime_ = new ::std::string;
  }
  sys_curtime_->assign(value);
}
inline void SystemPropertyMsg::set_sys_curtime(const char* value) {
  set_has_sys_curtime();
  if (sys_curtime_ == &::google::protobuf::internal::kEmptyString) {
    sys_curtime_ = new ::std::string;
  }
  sys_curtime_->assign(value);
}
inline void SystemPropertyMsg::set_sys_curtime(const char* value, size_t size) {
  set_has_sys_curtime();
  if (sys_curtime_ == &::google::protobuf::internal::kEmptyString) {
    sys_curtime_ = new ::std::string;
  }
  sys_curtime_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* SystemPropertyMsg::mutable_sys_curtime() {
  set_has_sys_curtime();
  if (sys_curtime_ == &::google::protobuf::internal::kEmptyString) {
    sys_curtime_ = new ::std::string;
  }
  return sys_curtime_;
}
inline ::std::string* SystemPropertyMsg::release_sys_curtime() {
  clear_has_sys_curtime();
  if (sys_curtime_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = sys_curtime_;
    sys_curtime_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void SystemPropertyMsg::set_allocated_sys_curtime(::std::string* sys_curtime) {
  if (sys_curtime_ != &::google::protobuf::internal::kEmptyString) {
    delete sys_curtime_;
  }
  if (sys_curtime) {
    set_has_sys_curtime();
    sys_curtime_ = sys_curtime;
  } else {
    clear_has_sys_curtime();
    sys_curtime_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional string sys_starTime = 2;
inline bool SystemPropertyMsg::has_sys_startime() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SystemPropertyMsg::set_has_sys_startime() {
  _has_bits_[0] |= 0x00000002u;
}
inline void SystemPropertyMsg::clear_has_sys_startime() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void SystemPropertyMsg::clear_sys_startime() {
  if (sys_startime_ != &::google::protobuf::internal::kEmptyString) {
    sys_startime_->clear();
  }
  clear_has_sys_startime();
}
inline const ::std::string& SystemPropertyMsg::sys_startime() const {
  return *sys_startime_;
}
inline void SystemPropertyMsg::set_sys_startime(const ::std::string& value) {
  set_has_sys_startime();
  if (sys_startime_ == &::google::protobuf::internal::kEmptyString) {
    sys_startime_ = new ::std::string;
  }
  sys_startime_->assign(value);
}
inline void SystemPropertyMsg::set_sys_startime(const char* value) {
  set_has_sys_startime();
  if (sys_startime_ == &::google::protobuf::internal::kEmptyString) {
    sys_startime_ = new ::std::string;
  }
  sys_startime_->assign(value);
}
inline void SystemPropertyMsg::set_sys_startime(const char* value, size_t size) {
  set_has_sys_startime();
  if (sys_startime_ == &::google::protobuf::internal::kEmptyString) {
    sys_startime_ = new ::std::string;
  }
  sys_startime_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* SystemPropertyMsg::mutable_sys_startime() {
  set_has_sys_startime();
  if (sys_startime_ == &::google::protobuf::internal::kEmptyString) {
    sys_startime_ = new ::std::string;
  }
  return sys_startime_;
}
inline ::std::string* SystemPropertyMsg::release_sys_startime() {
  clear_has_sys_startime();
  if (sys_startime_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = sys_startime_;
    sys_startime_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void SystemPropertyMsg::set_allocated_sys_startime(::std::string* sys_startime) {
  if (sys_startime_ != &::google::protobuf::internal::kEmptyString) {
    delete sys_startime_;
  }
  if (sys_startime) {
    set_has_sys_startime();
    sys_startime_ = sys_startime;
  } else {
    clear_has_sys_startime();
    sys_startime_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace player
}  // namespace proto
}  // namespace yishi
}  // namespace road
}  // namespace com

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_SystemPropertyMsg_2eproto__INCLUDED
